### PR TITLE
Add support for TEXT and NOTES

### PR DESCRIPTION
**Pull request by SomeCallMeTom**
Added support for text and notes layers

### CODE REVIEW

**Comment by GravityDeficient** [comment]
Does this work? Notes should be "Note" and you'd need a coordinator. Also currently I'm only looking at image types so additional logic is required to add Text items to the list. I'll setup a branch with the additional changes if you want to try it out.

**Comment by GravityDeficient** [comment]
Take a look at this branch
https://github.com/GravityDeficient/obr-external-links/tree/text-note-map--support

**Review by GravityDeficient — CHANGES_REQUESTED** [review]
Not merging this one, use - https://github.com/GravityDeficient/obr-external-links/tree/text-note-map--support

**Comment by SomeCallMeTom** [comment]
Not sure how I can test this.

Tried using the following link for the manifest
https://raw.githubusercontent.com/GravityDeficient/obr-external-links/text-note-map--support/public/manifest.json

**Comment by GravityDeficient** [comment]
It's been merged. You can run it from the main branch now.
https://obr-external-links.gravitydeficient.com/manifest.json

**Pull request closed without merging**
